PX4/DriverFramework

CMakeLists.txt, README.md, drivers/CMakeLists.txt, drivers/i2c/I2CDevObj.cpp, drivers/pressure/PressureSensor.hpp, drivers/pressure/test/CMakeLists.txt, drivers/pressure/test/main.cpp, framework/include/DevObj.hpp, framework/include/DisableCopy.hpp, framework/include/DriverFramework.hpp, framework/include/I2CDevObj.hpp, framework/include/VirtDevObj.hpp, framework/src/DevMgr.cpp, framework/src/DevObj.cpp, framework/src/DriverFramework.cpp, test/CMakeLists.txt, test/main.cpp, test/testdriver.hpp
Converted WorkHandle to a managed handle
=> Mark updates

framework/src/DevMgr.cpp
Thread sanitizer found a potential deadlock. Fixed.
=> Fixed potential deadlock

drivers/pressure/test/main.cpp
=> Fixed compliation warnings in PressureSensor test

Makefile, drivers/i2c/I2CDevObj.cpp, framework/include/DFList.hpp, framework/include/DevMgr.hpp, framework/include/DevObj.hpp, framework/include/I2CDevObj.hpp, framework/include/VirtDevObj.hpp, framework/src/CMakeLists.txt, framework/src/DFList.cpp, framework/src/DevMgr.cpp, framework/src/DevObj.cpp, framework/src/DriverFramework.cpp, test/main.cpp
=> Removed all use of C++ STL

.gitmodules, CMakeLists.txt, Makefile, drivers/bmp280/test/qurt/CMakeLists.txt, drivers/hmc5883/test/qurt/CMakeLists.txt, drivers/mpu9250/test/qurt/CMakeLists.txt, framework/src/DriverFramework.cpp, test/framework/CMakeLists.txt, test/framework/DFFrameworkTest.cpp, test/framework/DevMgrTest.hpp, test/framework/WorkMgrTest.cpp, test/framework/WorkMgrTest.hpp, test/framework/testdriver.hpp, test/qurt/CMakeLists.txt
=> Updated to latest cmake_hexagon

.gitmodules
This switches to PX4/dspal and adds a commit to comment out includes which were not found.
=> Fix includes

.gitmodules, drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp
With this the attitude estimator is working.
=> Gyro conversion

drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp
Tested on Snapdragon, seems to work and the values differ from sample to sample.
=> MPU9250: raise samplerate to 1kHz

framework/src/DriverFramework.cpp
After the bump from 250 Hz to 1000 Hz of the MPU9250, we get timeouts
again. The workaround is not to schedule any work which is closer than
100 us in the future. This seems to work for most cases but not with
100 % certainty.
=> framework: add the workaround to prevent timeouts

README.md
@julianoes please check if this is correct.
=> README: better document how the framework works

drivers/hmc5883/HMC5883.cpp, drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp, framework/include/ImuSensor.hpp, framework/src/DriverFramework.cpp, framework/src/SPIDevObj.cpp
This raises the sample rate from 500 Hz to 8 kHz using the MPU9250's FIFO register.
Bench tested on Snapdragon.
=> Faster sampling of MPU9250

framework/src/DriverFramework.cpp
This was causing problems for me on Ubuntu 14.04 with GCC 4.8.4. I'm not sure why the Firmware builds are fine.
=> silence GCC maybe uninitialized warnings

framework/src/DriverFramework.cpp, framework/src/WorkItems.cpp, framework/src/WorkItems.hpp, framework/src/WorkMgr.cpp
Fixes https://github.com/PX4/Firmware/issues/4646.
The commit which made the difference is 46e6573cd7eb455881e06a4bf38752156c247475.
Tested in SITL.
Let's merge it as soon travis is happy.
=> Fix unitialized handle

framework/src/DriverFramework.cpp
=> framework: remove printf

framework/src/DriverFramework.cpp
This is a workaroung for #91 for now.
=> framework: setsched_doesn't seem to work on QURT

.travis.yml, Makefile
This should add `make check-format` to travis.
=> Travis: check style

.travis.yml, drivers/lsm9ds1/CMakeLists.txt, drivers/lsm9ds1/LSM9DS1.cpp, drivers/lsm9ds1/LSM9DS1.hpp, drivers/lsm9ds1/test/CMakeLists.txt, drivers/lsm9ds1/test/main.cpp, drivers/lsm9ds1/test/test.cpp, framework/include/ImuSensor.hpp
Replaces #110, trying to get travis happy.
=> Adds LSM9DS1 IMU Sensor for Navio2 (rebased)

cmake/toolchains/Toolchain-bebop.cmake, cmake/toolchains/Toolchain-linux.cmake, cmake/toolchains/Toolchain-rpi2.cmake, drivers/ms5607/MS5607.cpp, drivers/ms5611/CMakeLists.txt, drivers/ms5611/MS5611.cpp, drivers/ms5611/MS5611.hpp, drivers/ms5611/test/CMakeLists.txt, drivers/ms5611/test/main.cpp, drivers/ms5611/test/test.cpp, framework/include/DriverFramework.hpp, framework/include/I2CDevObj.hpp, framework/src/DriverFramework.cpp, framework/src/I2CDevObj.cpp
=> MS5611 driver for RPi (rebased)

drivers/lsm9ds1/LSM9DS1.cpp, drivers/lsm9ds1/LSM9DS1.hpp, framework/src/SPIDevObj.cpp
This are some more fixes needed for the new LSM9DS1 driver.
FYI @mayanez.
=> Fixes for LSM9DS1

drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp, drivers/mpu9250/MPU9250_mag.cpp, framework/include/SPIDevObj.hpp, framework/src/SPIDevObj.cpp
@julianoes Please review this PR.
It should fix issue #89 .  
Issue reproduce
Run a simple script like below:
```
#!/bin/bash
for i in {1..1000}
do
./df_imu_test
done
```
Issue arise by luck. :)
When issue happened, run df_imu_test with my fix, then MPU9250 will work fine.
Attachment is my test log.
=> mpu9250: fix sometimes mpu9250 fails to initialize.

drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp, framework/src/SPIDevObj.cpp
Replacement for the older PR https://github.com/PX4/DriverFramework/pull/134
=> MPU9250: fix for edison build

drivers/mpu9250/MPU9250.cpp
@julianoes please review & merge
=> mpu9250: fix implicit float to double conversion

Makefile, drivers/bebop_bus/BebopBus.cpp, drivers/bebop_bus/BebopBus.hpp, drivers/bebop_bus/CMakeLists.txt, drivers/bebop_bus/test/CMakeLists.txt, drivers/bebop_bus/test/main.cpp, drivers/bebop_bus/test/test.cpp
This PR adds the I2C driver that communicates with the Parrot Bebop. The driver is flight tested, but still considered as beta. For example, setting the GPIOs does not work.
=> Driver BebopBus

README.md
=> README.md: added travis badge

CMakeLists.txt, Makefile
Updated cmake_hexagon for SLPI support, fixed indenting.
=> SLPI support

framework/src/DevObj.cpp
=> DevObj: fix race condition in work scheduling

CMakeLists.txt, Makefile, cmake/toolchains/Toolchain-bebop.cmake, cmake/toolchains/Toolchain-edison.cmake, cmake/toolchains/Toolchain-linux.cmake, cmake/toolchains/Toolchain-qurt.cmake, cmake/toolchains/Toolchain-rpi.cmake, drivers/bmp280/BMP280.cpp, drivers/hmc5883/HMC5883.cpp, drivers/isl29501/isl29501.cpp, drivers/lsm9ds1/LSM9DS1.hpp, drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp, drivers/trone/TROne.cpp, framework/include/DFLog.hpp, framework/include/DriverFramework.hpp, framework/include/ImuSensor.hpp, framework/include/WorkMgr.hpp, framework/src/DFDiag.cpp, framework/src/DriverFramework.cpp, framework/src/I2CDevObj.cpp, framework/src/SPIDevObj.cpp, framework/src/SyncObj.cpp, framework/src/Time.cpp
This changes the following defines:
__QURT -> __DF_QURT
__RPI -> __DF_RPI
__EDISON -> __DF_EDISON
__BEBOP -> __DF_BEBOP
__LINUX -> __DF_LINUX
Adresses #144.
=> Prepend DF to platform defines

CMakeLists.txt, Makefile
Added back __DF_QURT, updated cmake_hexagon
=> Fixed QuRT build

drivers/bmp280/test/qurt/CMakeLists.txt, drivers/hmc5883/test/qurt/CMakeLists.txt, drivers/mpu9250/test/qurt/CMakeLists.txt, test/qurt/CMakeLists.txt
New variable is used for ARM cross compiler
=> Updated cmake_hexagon

framework/src/DevMgr.cpp, framework/src/WorkItems.hpp
Added locks and missing initialization.
=> Fixes for coverity scan warnings

drivers/bebop_bus/BebopBus.cpp, drivers/bebop_bus/BebopBus.hpp
Did a test flight which went well. I need to test more and make sure the logging works.
The goal is to have motor rpm and desired rpm logged.
=> Pr bebop thrust

framework/include/DFList.hpp, framework/include/DevMgr.hpp, framework/include/DevObj.hpp, framework/include/DisableCopy.hpp, framework/include/HandleObj.hpp, framework/include/SyncObj.hpp, framework/include/WorkMgr.hpp
GCC or Clang pedantic doesn't like these.
=> remove unnecessary commas

.gitmodules, CMakeLists.txt, Makefile
Switch DriverFramework back to using ATLFlight/dspal
=> Use atl flight dspal

drivers/mpu9250/MPU9250.cpp, drivers/mpu9250/MPU9250.hpp
These are the requested changes for filtering and sampling rate. @julianoes can you please add this to the driverframework update https://github.com/PX4/Firmware/pull/6926?
=> change accel and gyro read/filter rates for snapdragon

.travis.yml, framework/src/DriverFramework.cpp
github.com/PX4/astyle is no longer available, so let's try the one that comes with Ubuntu.
=> travis: use packaged astyle instead of custom

framework/include/DevMgr.hpp, framework/include/DevObj.hpp, framework/src/DevMgr.cpp, framework/src/DevObj.cpp, test/framework/DevMgrTest.cpp, test/framework/DevMgrTest.hpp, test/framework/testdriver.hpp
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>
=> DevMgr/DevObj: remove updateNotify feature

framework/src/DriverFramework.cpp
This fixes a build error when compiled with DF_DEBUG.
Resolves #221.
=> framework: fix debug printf

drivers/ltc2946/LTC2946.cpp, drivers/ltc2946/LTC2946.hpp
This got changed during a review in PX4/Firmware and I forgot to change it in here...
=> fix ltc2946 _publish()
