PX4/DriverFramework

- framework/src/DFList.cpp
The `deleteNode` method is private and has a comment saying it needs
no internal locking and yet it had an call to `unlock`. This `unlock`
was causing `pthread_mutex_unlock` to be called on the same mutex
twice which according to the pthread docs invokes undefined behaviour,
in this case a SIGSEGV.
> DFList: Remove extraneous mutex unlock

- framework/src/DriverFramework.cpp
This one probably isn't strictly needed, but it stops thread debugging
tools complaining about g_start_thread.
> Add missing mutex

- drivers/mpu9250/MPU9250.hpp
This matches https://github.com/PX4/Firmware/blob/master/src/drivers/mpu9250/mpu9250.cpp#L461.
> MPU9250: gyro scale was wrong by factor 2

- framework/src/DriverFramework.cpp
This removes two workarounds:
- The one for pthread_cont_timedwait which was needed on Snapdragon, see #28.
- The one added after https://github.com/PX4/DriverFramework/commit/e62faaccae8775fd4dc237d4c43fb29a62603014, see #39.
> Workaround cleanup

- README.md
- framework/include/WorkMgr.hpp
- framework/src/DriverFramework.cpp
- test/framework/WorkMgrTest.cpp
Since the recent fix https://github.com/PX4/DriverFramework/commit/e62faaccae8775fd4dc237d4c43fb29a62603014 broke SITL (see #39) more debugging was needed.
The main bug was that every call to ```getWorkHandle()``` removed the 0th entry in ```g_work_items``` instead of the respective one.
The current state is tested in SITL as well as on the Snapdragon.
@mcharleb I'd appreciate it if you could review this PR.
> WorkMgr bugfixes

- drivers/bmp280/BMP280.cpp
- drivers/bmp280/BMP280.hpp
- drivers/hmc5883/HMC5883.cpp
- drivers/hmc5883/HMC5883.hpp
- drivers/mpu9250/MPU9250.cpp
- drivers/mpu9250/MPU9250.hpp
- framework/include/I2CDevObj.hpp
- framework/include/SPIDevObj.hpp
This brings proper support for the device id for MPU9250, BMP280, and HMC5883.
> Device ids

- framework/src/DriverFramework.cpp
The worker thread needs more stacksize, otherwise the _measure() call crashes once the delta angles are added in the MPU9250.
Tested on Snapdragon and SITL.
> framework: raise stacksize of worker thread

- drivers/mpu9250/MPU9250.hpp
This is needed to lower the risk of running into a pthread_cond_timedwait timeout.
It is related to #48 and #49.
> MPU9250: lower sample rate from 1kHz to 500Hz

- framework/src/DriverFramework.cpp
If CLOCK_MONOTONIC is used, pthread_cond_timedwait returns immediately
leading to 100% CPU use.
Tested on Snapdragon. This brings the CPU load down from ~ 150% of one CPU to ~ 50%.
FYI @liamstask
> framework: use CLOCK_MONOTONIC on Snapdragon Linux

- framework/src/DriverFramework.cpp
The pthread_cond_timedwait can be configured to use the monotonic clock,
at least on the Linux side on the Snapdragon. This is the proper fix for
the pthread_cond_timedwait that kept returning immediately. Switching to
CLOCK_REALTIME was only a workaround.
> framework: use monotonic clock for scheduling

- drivers/mpu9250/MPU9250.cpp
- framework/include/ImuSensor.hpp
Instead of calculating time offsets between sampling, it's easier to just assume a constant FIFO sampling interval inside `_publish`. All `_publish` needs to know is if it receives the last FIFO sample and should therefore wrap up and publish.
> Simpler integration

- framework/src/DriverFramework.cpp
This should fix #68.
It would also be a good idea to check if there's too much work & scheduling falls behind.
@LorenzMeier can you test if this improves things?
btw `make run` shows some failed tests, but the same happens on master (not reported as error in travis).
> HRTWorkQueue: avoid scheduling drift

- framework/src/DFList.cpp
- framework/src/DevMgr.cpp
- framework/src/DriverFramework.cpp
- test/framework/WorkMgrTest.cpp
Disambiguated use of static g_lock in 2 files.
Added tuning parameter to compensate for latency of pthread_cond_timedwait.
Deadlines are now usually within 1-3usec (execpt for 0usec delay).
Also fixed thread lock race conditions found using clang and thread sanitizer.
This has only been tested on Linux. Not yet ready to merge.
> WIP: latency improvement

- framework/include/DriverFramework.hpp
- framework/src/DFList.cpp
- framework/src/DevMgr.cpp
- framework/src/DriverFramework.cpp
- framework/src/SyncObj.cpp
- framework/src/Time.cpp
- test/framework/SyncObjTest.cpp
- test/framework/TimeTest.cpp
- test/framework/TimeTest.hpp
- test/framework/WorkMgrTest.cpp
The SyncObj unit test was disabled and that masked a but in DF. At some
point the clock was changed to CLOCK_MONOTONIC (except for Apple) but that breaks all
uses of pthread_cond_timedwait on Linux which MUST use CLOCK_REALTIME and on Linux
ideally DF would use CLOCK_REALTIME_RAW.
This PR is trying to resolve what happened to the clocks and to fix them
on Linux. The state on QuRT and NuttX is unknown.
> WIP: Clock fixes (Do not merge)

- framework/src/SPIDevObj.cpp
IMHO, this limitation doesn't make any sense. Hence, I suggest removing
it. This [post](https://github.com/PX4/DriverFramework/issues/66#issuecomment-220385398) has a more complete description.
> framework: fixed SPI bulkRead() on Raspberry Pi

- drivers/trone/TROne.cpp
If the scheduling is started before probe call, it seems to be busy
looping and blocking the HMC5883.
This fixes https://github.com/PX4/Firmware/issues/4639.
> trone: probe first and then start measure calls

- framework/include/DriverFramework.hpp
- framework/include/SyncObj.hpp
- framework/src/DevMgr.cpp
- framework/src/DriverFramework.cpp
- framework/src/SyncObj.cpp
- framework/src/Time.cpp
- framework/src/WorkItems.cpp
- test/framework/SyncObjTest.cpp
- test/framework/TimeTest.cpp
By providing waitOnSignal with a us resolution instead of just ms resolution we can save a big amount of CPU load for SITL (and presumably also on Snapdragon).
This should help with https://github.com/PX4/Firmware/issues/4656.
> Fix SITL CPU

- cmake/toolchains/Toolchain-rpi2.cmake
- framework/include/DriverFramework.hpp
This replaces #81.
Once travis is ok, we can merge this.
> framework: fix build for RPI2 (rebased)

- drivers/mpu9250/MPU9250.cpp
Fixes -Werror for Implicit conversion from float to double. This allows it build properly.
> Fixes Implicit cast in DF for MPU9250

- CMakeLists.txt
- test/framework/DFFrameworkTest.cpp
- test/framework/SyncObjTest.cpp
- test/framework/TimeTest.cpp
- test/framework/WorkMgrTest.cpp
Mac doesn't seem to be behaving very accurately, however, we can make
the tests pass by being quite generous. The proper approach might be to
play with scheduling options on Mac OS.
Should fix #3.
> test: get unit tests on Mac working again

- test/framework/DFFrameworkTest.cpp
- test/framework/TimeTest.cpp
- test/framework/WorkMgrTest.cpp
It didn't seem feasible to do the timing sensitive tests on travis,
therefore just comment them out and save the pain.
Related to #104.
> test: remove timing tests in travis

- drivers/bmp280/BMP280.cpp
- drivers/hmc5883/HMC5883.cpp
- drivers/isl29501/isl29501.cpp
- drivers/mpu9250/MPU9250.cpp
- drivers/trone/TROne.cpp
- framework/include/I2CDevObj.hpp
- framework/include/SPIDevObj.hpp
These calls were actually always failing, however this didn't lead to an
error because errno which was returned was 0.
Also, the file descriptor m_fd written by devOpen is later overwritten
anyway in I2C/SPIDevObj::start().
Removing all the devOpen/devClose functionality didn't break anything,
so it was presumably unused.
The unit tests of the framework and all drivers still pass, and PX4 still runs on Snappy.
Thanks @eyeam3 for catching this.
> drivers/framework: remove devOpen/devClose

- cmake/toolchains/Toolchain-rpi2.cmake
This lead to some weird effects when the toolchains of RPi wasn't installed but the Qualcomm one was.
FYI: @eyeam3
> cmake: don't force compilers

- .gitignore
- Makefile
- cmake/toolchains/Toolchain-bebop.cmake
- drivers/ms5607/CMakeLists.txt
- drivers/ms5607/MS5607.cpp
- drivers/ms5607/MS5607.hpp
- drivers/ms5607/test/CMakeLists.txt
- drivers/ms5607/test/main.cpp
- drivers/ms5607/test/test.cpp
- framework/include/I2CDevObj.hpp
- framework/src/I2CDevObj.cpp
This is a driver for the MS5607 barometer sensor. It is based on the MS5611 driver of the PX4/Firmware and adapted as needed.
Furthermore, the I2C functionality is extended for posix platforms. This is also based on the PX4/Firmware and tested on the Parrot Bebop. The communication should work on RPis, too, but is not tested so far.
> Add driver for MS5607 and I2C functionality for Bebop(Linux)

- drivers/ms5607/test/CMakeLists.txt
The MS5607 is only on Bebop, not Snapdragon, so no need to compile for QURT.
> ms5607: don't compile for QURT

- drivers/ms5611/MS5611.cpp
- drivers/ms5611/MS5611.hpp
It will seriously reduce other sensors's collect rate, and cause issue like FIFO overflow on MPU9250 and LSM9DS1.
It was very easily reproduce on rpi3+navio2, just start ms6511 and mpu9250 drivers.
This should be fix #74 .
> ms5611: fix sleep in work process will block WorkQueue schedule.

- framework/include/I2CDevObj.hpp
This fixes #119. The `_retries` variable was uninitialized which lead to many retries if unlucky.
> Fix I2C retries

- CMakeLists.txt
- framework/include/DFLog.hpp
__STDC_FORMAT_MACROS changes the behavior of inttypes.h to allow
defining format macros for printf-like functions. It needs to be defined
before any include is done, otherwise due to include chains and header
guards it may not take effect.
Instead of having to define it everywhere it is used, move the define to the
build system.
> Move __STDC_FORMAT_MACROS to build system

- .gitignore
- Makefile
- cmake/toolchains/Toolchain-rpi.cmake
- drivers/lsm9ds1/LSM9DS1.hpp
- framework/include/ImuSensor.hpp
- framework/src/SPIDevObj.cpp
The reason is that RPi2 and RPi3 are both compatible.
FYI @mayanez.
> RPi: just use RPI instead of RPI2

- Makefile
"make load" is a dspal target that projects often have to make it easier to push the images onto the target.
> Add "make load" for qurt platform

- framework/src/I2CDevObj.cpp
The var _retries will be decreased if write operation is failed.
If user do not reset the _retries variable manually, the _retries
will decrease to -1 and retrying for unexpected times. #119
> I2CDevObj: Preventing retries setting been modified.

- framework/src/DevObj.cpp
When `WorkMgr::getWorkHandle` is reached within `setSampleInterval`, we already have a valid scheduled task, so we need to release it first. Otherwise we end up having two scheduled tasks for the same callback, one with the previous sample interval, and one for the updated.
The faulty behavior can be verified with the accelsim in PX4 (https://github.com/PX4/Firmware/blob/master/src/platforms/posix/drivers/accelsim/accelsim.cpp). It's initialized with a rate of 400Hz and afterwards updates to 800Hz. But the measured update rate of `_measure` is 1200Hz.
@mcharleb maybe there is a better way than to do an expensive rescheduling for just changing the sampling rate?
> fix setSampleInterval: release the work handle before re-scheduling

- drivers/lsm9ds1/LSM9DS1.cpp
The datasheet is actually correct, so we don't need the confused
comment.
Thanks @kd0aij for raising this in https://github.com/PX4/DriverFramework/commit/6bdc8bce97c619a77276d183f88ee2d6efce4cbf.
> LSM9DS1: fix comment about coordinate systems

- CMakeLists.txt
Proprietary drivers cannot be built in tree so those need a
mechanism to be built out of tree
Signed-off-by: Mark Charlebois <mcharleb@qti.qualcomm.com>
> Added ability to build out of tree drivers

- drivers/lsm9ds1/LSM9DS1.cpp
sensor coordinate system of mag is different with others. MAG_X should be -MAG_X
http://www.st.com/content/ccc/resource/technical/document/datasheet/1e/3f/2a/d6/25/eb/48/46/DM00103319.pdf/files/DM00103319.pdf/jcr:content/translations/en.DM00103319.pdf 
page 10.
> LSM9DS1: fix mag coordinate

- drivers/mpu6050/MPU6050.cpp
- this improves flight performance very much
Signed-off-by: Roman <bapstroman@gmail.com>
> driver framework: mpu6050 activate imu dlpf (set to 44 Hz cutoff)

- drivers/bmp280/BMP280.cpp
- drivers/bmp280/BMP280.hpp
This is what @langxm1223 suggested a while ago in https://github.com/PX4/Firmware/issues/5243.
The changes are according to the datasheet.
This closes https://github.com/PX4/Firmware/issues/5243.
> Fix BMP280 calibration according to datasheet

- drivers/mpu9250/MPU9250.cpp
- drivers/mpu9250/MPU9250.hpp
- framework/include/ImuSensor.hpp
Change  sensor_id verification,both 0x71 and 0x73 are valid.
There are various kind of mpu9250 module in China.
The WHOAMI value of the MPU9250 sensor which I used  was 0x73.
I don't know why there are different WHOAMI values of them.
So I add the 0x73 support into the code.
I use the rpi to build the autopilot without pxfmini or navio.
Pxfmini and navio was not popular in China. I can hardly to purchase it.
So I use raspberry pi separately.
If use raspberry pi separately
and communicate with  MPU9250 sensor by SPI mode 
both IMU_DEVICE_ACC_GYRO and  IMU_DEVICE_MAG  should be defined as
"/dev/spidev0.1"(if you plug the sensor to spidev0.1),other wise the px4firmware can't work correctly.
> Fix the MPU9250_WHOAMI verification AND fixed the imusensor macro definition.

- cmake/df_common.cmake
- framework/src/Time.cpp
Although it compiles without this on new macOS versions, from my experiments, there is no CLOCK_MONOTONIC as of 10.12.1.
This also causes the issue below because pthread_cond_timedwait returns immediately causing the work queue to infinite loop:
- Fixes https://github.com/PX4/Firmware/issues/6792
> Fix absolute time for new OS X versions

- Makefile
- cmake/toolchains/Toolchain-ocpoc.cmake
- drivers/bmp280/CMakeLists.txt
- drivers/hmc5883/HMC5883.hpp
- drivers/ms5611/MS5611.cpp
- drivers/ms5611/MS5611.hpp
- framework/include/BaroSensor.hpp
- framework/include/I2CDevObj.hpp
- framework/include/ImuSensor.hpp
- framework/include/SPIDevObj.hpp
- framework/src/SPIDevObj.cpp
This PR introduces necessary changes to support the Aerotenna OcPoC flight controller.
Aside from device path changes, we ran into issues with the MS5611 baro when we first switched to using it in SPI mode - the baro would return nothing for temperature and pressure. The issue is fixed with the addition of a new SPIDevObj function which is currently only applied for OcPoC (see commits 427e654 and 2d5ea38).
> Add Support for Aerotenna OcPoC Hardware

- .travis.yml
This should fix the build in precise (12.04) which fails because of deb
backports.
> travis: try to compile with gcc and clang

- framework/src/DevObj.cpp
Some drivers want to implement a custom callback scheme, hence
won't use the DevObj/WorkMgr for this.
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>
> DevObj: don't force drivers to specify a callback period

- framework/src/DFList.cpp
- framework/src/DriverFramework.cpp
This removes some unneeded locks. Locking shows up as one of the top contributors in terms of CPU cycles when running PX4 SITL.
I'm sure there are more improvements that can be done.
> Some locking improvements

- framework/include/ImuSensor.hpp
On PX4 master, the MPU6050 failed to initialize with the following error:
```
388329 Error: I2CDevObj::start failed on ::open() /dev/iic-2
388453 DevObj start failed
388507 Unable to open the device path: /dev/iic-2
ERROR [df_mpu6050_wrapper] MPU6050 start fail: -1
ERROR [df_mpu6050_wrapper] DfMPU6050Wrapper start failed
```
Now it is happy:
```
500159 IMU temperature initialized to: 52.085880
```
> Fix MPU6050 on Bebop 2

- framework/src/DriverFramework.cpp
- framework/src/SyncObj.cpp
- framework/src/Time.cpp
This adds some ifdefs to make sure that pthread_cond_timedwait is used
from the PX4 platform code if this happens to be a PX4 build.
> framework: forward time calls to PX4 if PX4 build

- framework/src/CMakeLists.txt
- framework/src/I2CDevObj.cpp
This is a part of a possible fix for
https://github.com/PX4/Firmware/issues/11137
This should not interfere with standalone builds of DriverFramework, but should
check whether i2c-dev.h file on a builder's system is sane when built as
a part of PX4 firmware.
Signed-off-by: sfalexrog <sfalexrog@gmail.com>
> framework: Attempt to check i2c-dev.h for sanity
